### ISSUE TITLE
Add screenshot / gif to readme

### ISSUE THREAD

**Issue by mweststrate** [motion/mobx-formatters#1]
This looks like a pretty cool utility! Would you mind adding screenshot or gif to the readme, so that the value becomes immediately clear? Thanks!

**Comment by natew** [comment]
Basic screen added 6cde8f355ead1262e75cd6dcaf1643c678427ca7

**Comment by mweststrate** [comment]
😀

Op vr 16 jun. 2017 05:32 schreef Nate Wienert <notifications@github.com>:
